# Generated by Django 5.1.15 on 2026-05-07 08:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_used_hrs', models.FloatField()),
                ('total_distance_miles', models.FloatField()),
                ('total_drive_minutes', models.IntegerField()),
                ('avg_mph', models.FloatField()),
                ('cycle_exceeded', models.BooleanField(default=False)),
                ('summary_note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('kind', models.CharField(choices=[('start', 'Start'), ('pickup', 'Pickup'), ('fuel', 'Fuel'), ('break30', '30-min Break'), ('rest10', '10-hr Rest'), ('dropoff', 'Dropoff')], max_length=16)),
                ('location_label', models.CharField(blank=True, default='', max_length=255)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('arrive_minute', models.IntegerField()),
                ('depart_minute', models.IntegerField()),
                ('miles_from_start', models.FloatField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trips.trip')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='DutySegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_index', models.IntegerField()),
                ('status', models.CharField(choices=[('off', 'Off Duty'), ('sleeper', 'Sleeper Berth'), ('driving', 'Driving'), ('on_duty', 'On Duty (not driving)')], max_length=16)),
                ('start_minute', models.IntegerField()),
                ('end_minute', models.IntegerField()),
                ('remark', models.CharField(blank=True, default='', max_length=255)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='trips.trip')),
            ],
            options={
                'ordering': ['day_index', 'start_minute'],
            },
        ),
    ]
